### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [raphadorneles10/dw-t23#2]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

O principal problema da sua entrega está na falta de otimização no uso do seu código. Note a quantidade de código duplicado de propriedades entre `Pendentes`, `Concluidos` e  `Excluidos`. 

https://github.com/raphadorneles10/dw-t23/blob/663514b4712b1aabdeba664e61f7d5e7aed9fb25/influensers/excluidos.css#L29-L57

Você pode evitar isso fazendo uso de duas classes. Adicionando em uma classe as propriedades comuns e tratando as exceções (ou sobreescritas) em outra classe. Veja um exemplo abaixo. 

```css
.menu {
    border-radius: 80px;
    border: 80px;
    padding: 13px;
    margin-right: 6px;
    text-decoration: none;
}

.excluida {
    color: rgb(255, 255, 255);
    background-color: red;
}
```

```html
<a class="menu excluida" href="excluidas.html"> Excluidas </a>
```

**Nota:** 8.5

### Comentarios

https://github.com/raphadorneles10/dw-t23/blob/663514b4712b1aabdeba664e61f7d5e7aed9fb25/influensers/excluidos.css#L95-L100

Existem várias partes do seu código mal indentado. 

Você pode aplicar a indentação automatica do VS Code seguindo os passos:
1) CTRL + p
2) Digite "> format document" (Note o `>`) 

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
